<h1>Images tensors<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-файла-изображения" data-toc-modified-id="Загрузка-файла-изображения-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка файла изображения</a></span></li><li><span><a href="#Изменение-схемы-изображения" data-toc-modified-id="Изменение-схемы-изображения-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Изменение схемы изображения</a></span></li><li><span><a href="#Нормализация-данных" data-toc-modified-id="Нормализация-данных-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Нормализация данных</a></span></li><li><span><a href="#Загрузка-данных-в-специализированном-формате" data-toc-modified-id="Загрузка-данных-в-специализированном-формате-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Загрузка данных в специализированном формате</a></span></li></ul></div>

In [10]:
import imageio
import torch
import os

### Загрузка файла изображения

In [2]:
img_arr = imageio.imread('/Users/alexfil/Desktop/PyTorch/RgAAAgO_X-A-1920.jpg')

/var/folders/yj/05csyfjn179703hvgy2jqdqm0000gn/T/ipykernel_24224/93083565.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('/Users/alexfil/Desktop/PyTorch/RgAAAgO_X-A-1920.jpg')


In [3]:
img_arr.shape

(768, 1024, 3)

Для PyTorch необходима схема измерений C x H x W (каналы, высота, ширина)

### Изменение схемы изображения

In [6]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [7]:
out.shape

torch.Size([3, 768, 1024])

In [48]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [49]:
data_dir = '/Users/alexfil/Desktop/PyTorch/data/cats'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']

In [50]:
filenames

['cat1.png', 'cat2.png', 'cat3.png']

In [51]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3]
    batch[i] = img_t

/var/folders/yj/05csyfjn179703hvgy2jqdqm0000gn/T/ipykernel_24224/4177784309.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [52]:
img_t.shape

torch.Size([3, 256, 256])

In [53]:
batch.shape

torch.Size([3, 3, 256, 256])

### Нормализация данных

In [54]:
batch = batch.float()
batch /= 255.0

In [46]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [55]:
batch[1]

tensor([[[0.7922, 0.7569, 0.7451,  ..., 0.0510, 0.0510, 0.0471],
         [0.7804, 0.7529, 0.7412,  ..., 0.0549, 0.0549, 0.0549],
         [0.7765, 0.7569, 0.7373,  ..., 0.0471, 0.0471, 0.0471],
         ...,
         [0.3647, 0.3216, 0.2980,  ..., 0.1412, 0.1412, 0.1412],
         [0.2941, 0.2667, 0.3961,  ..., 0.1412, 0.1412, 0.1451],
         [0.3333, 0.4039, 0.3529,  ..., 0.1412, 0.1451, 0.1490]],

        [[0.5922, 0.5451, 0.5216,  ..., 0.0353, 0.0353, 0.0314],
         [0.5922, 0.5490, 0.5255,  ..., 0.0431, 0.0431, 0.0431],
         [0.5961, 0.5608, 0.5255,  ..., 0.0431, 0.0431, 0.0431],
         ...,
         [0.2235, 0.1765, 0.1529,  ..., 0.1020, 0.1020, 0.1020],
         [0.1294, 0.1020, 0.2314,  ..., 0.1020, 0.1020, 0.1059],
         [0.1569, 0.2275, 0.1765,  ..., 0.1020, 0.1059, 0.1098]],

        [[0.2667, 0.2078, 0.1725,  ..., 0.0235, 0.0235, 0.0196],
         [0.2627, 0.2118, 0.1725,  ..., 0.0235, 0.0235, 0.0235],
         [0.2627, 0.2196, 0.1725,  ..., 0.0235, 0.0235, 0.

In [56]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [57]:
batch[1]

tensor([[[ 0.9595,  0.7999,  0.7467,  ..., -2.3915, -2.3915, -2.4092],
         [ 0.9063,  0.7822,  0.7290,  ..., -2.3738, -2.3738, -2.3738],
         [ 0.8886,  0.7999,  0.7113,  ..., -2.4092, -2.4092, -2.4092],
         ...,
         [-0.9731, -1.1681, -1.2745,  ..., -1.9837, -1.9837, -1.9837],
         [-1.2922, -1.4163, -0.8312,  ..., -1.9837, -1.9837, -1.9660],
         [-1.1149, -0.7958, -1.0263,  ..., -1.9837, -1.9660, -1.9482]],

        [[ 0.6908,  0.4632,  0.3494,  ..., -2.0024, -2.0024, -2.0214],
         [ 0.6908,  0.4822,  0.3684,  ..., -1.9645, -1.9645, -1.9645],
         [ 0.7098,  0.5391,  0.3684,  ..., -1.9645, -1.9645, -1.9645],
         ...,
         [-1.0920, -1.3196, -1.4334,  ..., -1.6800, -1.6800, -1.6800],
         [-1.5472, -1.6800, -1.0541,  ..., -1.6800, -1.6800, -1.6610],
         [-1.4144, -1.0730, -1.3196,  ..., -1.6800, -1.6610, -1.6420]],

        [[-0.4598, -0.7644, -0.9472,  ..., -1.7190, -1.7190, -1.7394],
         [-0.4801, -0.7441, -0.9472,  ..., -1

### Загрузка данных в специализированном формате

In [58]:
dir_path = '/Users/alexfil/Desktop/PyTorch/data/2-LUNG 3.0 B70f-04083'
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/21 files (4.8  Warning: missing file after '/Users/alexfil/Desktop/PyTorch/data/2-LUNG 3.0 B70f-04083/000011.dcm'
Reading DICOM (examining files): 1/21 files (4.8  Warning: missing file after '/Users/alexfil/Desktop/PyTorch/data/2-LUNG 3.0 B70f-04083/000017.dcm'
Reading DICOM (examining files): 1/21 files (4.8%21/21 files (100.0%)
  Found 5 correct series.
Reading DICOM (loading data): 4/4  (100.0%)


(4, 512, 512)

In [59]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 0)

In [60]:
vol.shape

torch.Size([1, 4, 512, 512])

In [61]:
vol

tensor([[[[ -985.,  -990.,  -999.,  ..., -1017., -1008.,  -971.],
          [-1016.,  -984.,  -963.,  ..., -1000., -1009.,  -999.],
          [-1024., -1008.,  -996.,  ...,  -979., -1021.,  -987.],
          ...,
          [ -920.,  -942.,  -944.,  ...,  -893.,  -917.,  -955.],
          [ -871.,  -879.,  -905.,  ...,  -895.,  -869.,  -867.],
          [ -876.,  -855.,  -873.,  ...,  -933.,  -982.,  -936.]],

         [[-1022., -1011.,  -983.,  ..., -1013.,  -980.,  -967.],
          [-1022., -1005., -1012.,  ...,  -948.,  -966., -1008.],
          [ -991.,  -965.,  -993.,  ...,  -964., -1011.,  -996.],
          ...,
          [ -858.,  -899.,  -950.,  ...,  -939.,  -868.,  -827.],
          [ -948.,  -914.,  -918.,  ...,  -968.,  -978.,  -946.],
          [ -921.,  -874.,  -914.,  ...,  -898.,  -910.,  -934.]],

         [[-1014.,  -981., -1024.,  ...,  -981.,  -985.,  -999.],
          [-1010.,  -971., -1004.,  ...,  -934.,  -963., -1023.],
          [-1022.,  -981.,  -941.,  ...,  