<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Создание-тензора" data-toc-modified-id="Создание-тензора-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Создание тензора</a></span></li><li><span><a href="#Доступ-к-тензорам-по-индексам" data-toc-modified-id="Доступ-к-тензорам-по-индексам-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Доступ к тензорам по индексам</a></span></li><li><span><a href="#Поименованные-тензоры" data-toc-modified-id="Поименованные-тензоры-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Поименованные тензоры</a></span></li><li><span><a href="#Работа-с-атрибутом-dtype-тензоров" data-toc-modified-id="Работа-с-атрибутом-dtype-тензоров-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Работа с атрибутом dtype тензоров</a></span></li><li><span><a href="#API-тензоров" data-toc-modified-id="API-тензоров-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>API тензоров</a></span></li><li><span><a href="#Доступ-к-хранилищу-по-индексу" data-toc-modified-id="Доступ-к-хранилищу-по-индексу-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Доступ к хранилищу по индексу</a></span></li><li><span><a href="#Модификация&nbsp;хранимых-значений:-операции-с-заменой-на-месте" data-toc-modified-id="Модификация&nbsp;хранимых-значений:-операции-с-заменой-на-месте-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Модификация&nbsp;хранимых значений: операции с заменой на месте</a></span></li><li><span><a href="#Представления-хранилища-другого-тензора" data-toc-modified-id="Представления-хранилища-другого-тензора-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Представления хранилища другого тензора</a></span></li><li><span><a href="#Транспонирование-без-копирования" data-toc-modified-id="Транспонирование-без-копирования-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Транспонирование без копирования</a></span></li><li><span><a href="#Транспонирование-при-более-высокой-размерности" data-toc-modified-id="Транспонирование-при-более-высокой-размерности-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Транспонирование при более высокой размерности</a></span></li><li><span><a href="#Непрерывные-тензоры" data-toc-modified-id="Непрерывные-тензоры-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Непрерывные тензоры</a></span></li><li><span><a href="#Совместимость-с-NumPy" data-toc-modified-id="Совместимость-с-NumPy-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Совместимость с NumPy</a></span></li><li><span><a href="#Сериализация-тензоров" data-toc-modified-id="Сериализация-тензоров-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Сериализация тензоров</a></span></li><li><span><a href="#Сериализация-в-HDF5" data-toc-modified-id="Сериализация-в-HDF5-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Сериализация в HDF5</a></span></li><li><span><a href="#Упражнения" data-toc-modified-id="Упражнения-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Упражнения</a></span></li></ul></div>

In [1]:
import torch

### Создание тензора

In [2]:
a = torch.ones(3)

In [3]:
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2

In [7]:
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)

In [9]:
points

tensor([0., 0., 0., 0., 0., 0.])

In [10]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [11]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [12]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [15]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points.shape

torch.Size([3, 2])

In [17]:
points = torch.zeros(3, 2)

In [18]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [20]:
points[0, 1]

tensor(1.)

In [21]:
points[0]

tensor([4., 1.])

### Доступ к тензорам по индексам

In [22]:
some_list = list(range(6))

In [23]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [24]:
some_list[1:4]

[1, 2, 3]

In [25]:
some_list[1:4]

[1, 2, 3]

In [26]:
some_list[1:]

[1, 2, 3, 4, 5]

In [27]:
some_list[:4]

[0, 1, 2, 3]

In [28]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [29]:
some_list[1:4:2]

[1, 3]

In [30]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [32]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [33]:
points[1:, 0]

tensor([5., 2.])

In [34]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### Поименованные тензоры

In [35]:
img_t = torch.randn(3, 5, 5)

In [36]:
img_t

tensor([[[ 2.0594, -1.1983,  0.3290, -1.8601,  0.0486],
         [-0.1446, -0.1555,  0.2338, -0.5177,  0.2297],
         [ 0.2306,  1.9629,  0.9200, -0.7424, -0.2412],
         [ 1.5311, -0.6206, -0.5839,  1.1726,  0.9414],
         [-1.0170,  0.4645,  2.3899,  0.0085, -0.0201]],

        [[ 0.5855, -0.1619, -0.9564,  1.4804, -0.0721],
         [ 0.4158, -1.1565,  0.5702,  0.0207,  1.9903],
         [ 0.9842,  0.1993, -0.7904,  1.1505, -0.2505],
         [ 0.0432, -0.5206, -1.9137, -1.3364, -0.6051],
         [ 0.4096, -0.1794, -0.6533,  1.6545,  0.0710]],

        [[ 0.8793, -1.3736, -0.0309,  1.4345,  0.2535],
         [-0.3127, -1.9432,  1.0717,  0.9928,  1.3696],
         [-0.1957,  0.1714,  0.3461, -0.7151,  1.4787],
         [ 0.0750, -0.3427,  1.1853, -0.9801, -1.1877],
         [-1.6335, -0.0916,  1.3507, -0.5809,  0.2856]]])

In [37]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [38]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [39]:
batch_t = torch.randn(2, 3, 5, 5)

In [40]:
batch_t

tensor([[[[-0.9885,  1.9630, -0.3908,  0.2852,  0.4944],
          [ 0.8555, -2.8186, -2.7398, -1.3005,  0.0116],
          [ 0.1138, -0.5771, -1.9207, -1.5538, -1.2930],
          [ 0.6696, -3.1920,  0.1101, -0.1137, -1.3891],
          [-0.3104, -0.6786,  0.7506, -0.9528, -0.7794]],

         [[-0.4446, -0.6219, -0.9445, -0.1244, -0.9197],
          [ 0.6699, -1.0939, -0.9634, -1.5145, -1.2606],
          [ 0.3408,  0.3088,  0.8663,  0.0494, -0.1625],
          [ 0.6670,  2.1474,  0.4168, -1.2767, -1.1116],
          [ 1.8378,  0.5856, -0.8848, -0.7889,  0.6737]],

         [[ 1.7250, -1.1393, -0.1125, -1.2075, -0.2323],
          [ 0.0321, -1.0588,  2.0203,  0.3832, -0.3045],
          [-0.5751,  1.4706, -1.3102,  0.6328,  0.0070],
          [-1.2212, -0.8246, -0.9820,  0.0082, -1.8507],
          [ 0.9813, -0.3749,  0.8862,  0.7321, -1.4280]]],


        [[[ 0.1449,  1.5068,  0.9217, -1.8479,  1.0136],
          [-0.7324, -0.9941,  0.2639, -1.1473,  1.8293],
          [ 0.4612, -0.

In [41]:
img_gray_naive = img_t.mean(-3)

In [42]:
img_gray_naive

tensor([[ 1.1747, -0.9113, -0.2194,  0.3516,  0.0767],
        [-0.0138, -1.0851,  0.6253,  0.1653,  1.1965],
        [ 0.3397,  0.7779,  0.1586, -0.1023,  0.3290],
        [ 0.5497, -0.4946, -0.4374, -0.3813, -0.2838],
        [-0.7470,  0.0645,  1.0291,  0.3607,  0.1122]])

In [43]:
batch_gray_naive = batch_t.mean(-3)

In [44]:
batch_gray_naive

tensor([[[ 0.0973,  0.0673, -0.4826, -0.3489, -0.2192],
         [ 0.5192, -1.6571, -0.5610, -0.8106, -0.5178],
         [-0.0402,  0.4008, -0.7882, -0.2906, -0.4828],
         [ 0.0385, -0.6231, -0.1517, -0.4607, -1.4505],
         [ 0.8362, -0.1560,  0.2506, -0.3365, -0.5112]],

        [[-0.3266,  1.0825, -0.3139, -0.9398,  0.3987],
         [-0.5681, -0.1931,  0.4190, -0.3149,  0.5711],
         [-0.4812, -0.1604,  0.5428, -0.1779, -0.4844],
         [ 0.6143,  1.0377,  0.1077, -0.2393, -0.2969],
         [ 0.7588, -0.5109,  0.0060,  0.1765, -0.6712]]])

In [45]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [46]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [47]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [48]:
img_weights = (img_t * unsqueezed_weights)

In [49]:
img_weights

tensor([[[ 0.4378, -0.2548,  0.0700, -0.3955,  0.0103],
         [-0.0307, -0.0331,  0.0497, -0.1101,  0.0488],
         [ 0.0490,  0.4173,  0.1956, -0.1578, -0.0513],
         [ 0.3255, -0.1319, -0.1241,  0.2493,  0.2001],
         [-0.2162,  0.0988,  0.5081,  0.0018, -0.0043]],

        [[ 0.4187, -0.1158, -0.6840,  1.0588, -0.0516],
         [ 0.2974, -0.8271,  0.4078,  0.0148,  1.4234],
         [ 0.7039,  0.1426, -0.5653,  0.8228, -0.1791],
         [ 0.0309, -0.3723, -1.3687, -0.9558, -0.4328],
         [ 0.2930, -0.1283, -0.4672,  1.1833,  0.0508]],

        [[ 0.0635, -0.0992, -0.0022,  0.1036,  0.0183],
         [-0.0226, -0.1403,  0.0774,  0.0717,  0.0989],
         [-0.0141,  0.0124,  0.0250, -0.0516,  0.1068],
         [ 0.0054, -0.0247,  0.0856, -0.0708, -0.0858],
         [-0.1179, -0.0066,  0.0975, -0.0419,  0.0206]]])

In [50]:
batch_weights = (batch_t * unsqueezed_weights)

In [51]:
batch_weights

tensor([[[[-2.1015e-01,  4.1734e-01, -8.3089e-02,  6.0628e-02,  1.0511e-01],
          [ 1.8188e-01, -5.9923e-01, -5.8248e-01, -2.7649e-01,  2.4652e-03],
          [ 2.4196e-02, -1.2270e-01, -4.0834e-01, -3.3035e-01, -2.7489e-01],
          [ 1.4236e-01, -6.7862e-01,  2.3400e-02, -2.4179e-02, -2.9533e-01],
          [-6.5992e-02, -1.4427e-01,  1.5957e-01, -2.0256e-01, -1.6570e-01]],

         [[-3.1801e-01, -4.4479e-01, -6.7553e-01, -8.8936e-02, -6.5775e-01],
          [ 4.7914e-01, -7.8235e-01, -6.8901e-01, -1.0832e+00, -9.0162e-01],
          [ 2.4374e-01,  2.2087e-01,  6.1959e-01,  3.5302e-02, -1.1625e-01],
          [ 4.7707e-01,  1.5358e+00,  2.9812e-01, -9.1311e-01, -7.9504e-01],
          [ 1.3144e+00,  4.1882e-01, -6.3283e-01, -5.6420e-01,  4.8183e-01]],

         [[ 1.2455e-01, -8.2260e-02, -8.1206e-03, -8.7183e-02, -1.6771e-02],
          [ 2.3161e-03, -7.6444e-02,  1.4587e-01,  2.7668e-02, -2.1984e-02],
          [-4.1522e-02,  1.0618e-01, -9.4599e-02,  4.5685e-02,  5.0887e-

In [52]:
img_gray_weighted = img_weights.sum(-3)

In [53]:
img_gray_weighted

tensor([[ 0.9201, -0.4697, -0.6163,  0.7669, -0.0229],
        [ 0.2440, -1.0005,  0.5349, -0.0236,  1.5711],
        [ 0.7388,  0.5723, -0.3447,  0.6134, -0.1237],
        [ 0.3618, -0.5290, -1.4072, -0.7772, -0.3184],
        [-0.0412, -0.0361,  0.1384,  1.1431,  0.0671]])

In [54]:
batch_gray_weighted = batch_weights.sum(-3)

In [55]:
batch_gray_weighted

tensor([[[-0.4036, -0.1097, -0.7667, -0.1155, -0.5694],
         [ 0.6633, -1.4580, -1.1256, -1.3320, -0.9211],
         [ 0.2264,  0.2043,  0.1166, -0.2494, -0.3906],
         [ 0.5313,  0.7976,  0.2506, -0.9367, -1.2240],
         [ 1.3192,  0.2475, -0.4093, -0.7139,  0.2130]],

        [[ 0.2398,  1.0571, -0.6794,  0.0801, -0.1437],
         [-0.2178,  0.1346,  0.1546,  0.4125, -0.1593],
         [-0.7035,  0.0031,  0.0477, -0.3795, -0.0997],
         [ 0.7109,  0.6595, -0.1670,  0.1652, -0.2173],
         [ 0.7822, -1.2279, -0.6018,  0.3246,  0.1142]]])

In [56]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [57]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [58]:
img_gray_weighted_fancy

tensor([[ 0.9201, -0.4697, -0.6163,  0.7669, -0.0229],
        [ 0.2440, -1.0005,  0.5349, -0.0236,  1.5711],
        [ 0.7388,  0.5723, -0.3447,  0.6134, -0.1237],
        [ 0.3618, -0.5290, -1.4072, -0.7772, -0.3184],
        [-0.0412, -0.0361,  0.1384,  1.1431,  0.0671]])

In [59]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

/var/folders/yj/05csyfjn179703hvgy2jqdqm0000gn/T/ipykernel_98677/1901091524.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1911.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


In [60]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [61]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [62]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [63]:
img_named

tensor([[[ 2.0594, -1.1983,  0.3290, -1.8601,  0.0486],
         [-0.1446, -0.1555,  0.2338, -0.5177,  0.2297],
         [ 0.2306,  1.9629,  0.9200, -0.7424, -0.2412],
         [ 1.5311, -0.6206, -0.5839,  1.1726,  0.9414],
         [-1.0170,  0.4645,  2.3899,  0.0085, -0.0201]],

        [[ 0.5855, -0.1619, -0.9564,  1.4804, -0.0721],
         [ 0.4158, -1.1565,  0.5702,  0.0207,  1.9903],
         [ 0.9842,  0.1993, -0.7904,  1.1505, -0.2505],
         [ 0.0432, -0.5206, -1.9137, -1.3364, -0.6051],
         [ 0.4096, -0.1794, -0.6533,  1.6545,  0.0710]],

        [[ 0.8793, -1.3736, -0.0309,  1.4345,  0.2535],
         [-0.3127, -1.9432,  1.0717,  0.9928,  1.3696],
         [-0.1957,  0.1714,  0.3461, -0.7151,  1.4787],
         [ 0.0750, -0.3427,  1.1853, -0.9801, -1.1877],
         [-1.6335, -0.0916,  1.3507, -0.5809,  0.2856]]],
       names=('channels', 'rows', 'columns'))

In [64]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [65]:
gray_named

tensor([[ 0.9201, -0.4697, -0.6163,  0.7669, -0.0229],
        [ 0.2440, -1.0005,  0.5349, -0.0236,  1.5711],
        [ 0.7388,  0.5723, -0.3447,  0.6134, -0.1237],
        [ 0.3618, -0.5290, -1.4072, -0.7772, -0.3184],
        [-0.0412, -0.0361,  0.1384,  1.1431,  0.0671]],
       names=('rows', 'columns'))

In [66]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

### Работа с атрибутом dtype тензоров

In [67]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [68]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [69]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [70]:
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [71]:
double_points = torch.zeros(10, 2).double()

In [72]:
double_points = torch.ones(10, 2).short()

In [73]:
double_points = torch.zeros(10, 2).to(torch.double)

In [74]:
double_points = torch.ones(10, 2).to(torch.short)

In [75]:
points_64 = torch.rand(5, dtype=torch.double)

In [76]:
points_64

tensor([0.4884, 0.2814, 0.9483, 0.8298, 0.8415], dtype=torch.float64)

In [77]:
points_short = points_64.to(torch.short)

In [78]:
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [79]:
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

### API тензоров

In [80]:
a = torch.ones(3, 2)

In [81]:
a_t = torch.transpose(a, 0, 1)

In [82]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [83]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [84]:
a = torch.ones(3, 2)

In [85]:
a_t = a.transpose(0, 1)

In [86]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### Доступ к хранилищу по индексу

In [87]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [88]:
points.storage()

/var/folders/yj/05csyfjn179703hvgy2jqdqm0000gn/T/ipykernel_98677/2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [89]:
points_storage = points.storage()

In [90]:
points_storage[0]

4.0

In [91]:
points.storage()[1]

1.0

In [92]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0

In [93]:
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

### Модификация хранимых значений: операции с заменой на месте

In [94]:
a = torch.ones(3, 2)
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Представления хранилища другого тензора

In [95]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [96]:
second_point = points[1]

In [97]:
second_point

tensor([5., 3.])

In [98]:
second_point.storage_offset()

2

In [99]:
second_point.size()

torch.Size([2])

In [100]:
second_point.shape

torch.Size([2])

In [101]:
points.stride()

(2, 1)

In [102]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [103]:
second_point = points[1]

In [104]:
second_point.size()

torch.Size([2])

In [105]:
second_point.storage_offset()

2

In [106]:
second_point.stride()

(1,)

In [107]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0

In [108]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [109]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0

In [110]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### Транспонирование без копирования

In [111]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [112]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [113]:
points_t = points.t()

In [114]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [115]:
id(points.storage()) == id(points_t.storage())

False

In [116]:
points.stride()

(2, 1)

In [117]:
points_t.stride()

(1, 2)

### Транспонирование при более высокой размерности

In [129]:
some_t = torch.ones(3, 4, 5)

In [130]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [131]:
some_t.shape

torch.Size([3, 4, 5])

In [141]:
transpose_t = some_t.transpose(0, 2)

In [142]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [146]:
transpose_t.shape

torch.Size([5, 4, 3])

In [147]:
some_t.stride()

(20, 5, 1)

In [148]:
transpose_t.stride()

(1, 5, 20)

### Непрерывные тензоры

In [149]:
points.is_contiguous()

True

In [150]:
points_t.is_contiguous()

False

In [151]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [157]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [152]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [153]:
points_t.stride()

(1, 2)

In [154]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [155]:
points_t_cont.stride()

(3, 1)

In [156]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### Совместимость с NumPy

In [159]:
points = torch.ones(3, 4)
points 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [160]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [161]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Сериализация тензоров

In [162]:
torch.save(points, '/Users/alexfil/Desktop/PyTorch/data/ourpoints.t')

In [163]:
with open('/Users/alexfil/Desktop/PyTorch/data/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [164]:
points = torch.load('/Users/alexfil/Desktop/PyTorch/data/ourpoints.t')

In [165]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [166]:
with open('/Users/alexfil/Desktop/PyTorch/data/ourpoints.t', 'rb') as f:
    points = torch.load(f)

In [167]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Сериализация в HDF5

In [168]:
import h5py

In [169]:
f = h5py.File('/Users/alexfil/Desktop/PyTorch/data/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [170]:
f = h5py.File('/Users/alexfil/Desktop/PyTorch/data/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [171]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [172]:
last_points = torch.from_numpy(dset[-2:])
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [173]:
f.close()

### Упражнения

Создайте тензор a из list(range(9)). Попробуйте догадаться, какими будут его размер, сдвиг и шаг, а потом проверьте свои догадки.

In [212]:
a = torch.tensor(list(range(9)))

In [213]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [214]:
a.stride() #шаг

(1,)

In [215]:
a.storage_offset() #сдвиг

0

Создайте новый тензор с помощью команды b = a.view(3, 3) Что делает функция view? Убедитесь, что у тензоров a и b одно хранилище

In [216]:
b = a.view(3, 3)

In [217]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [218]:
id(a.storage()) == id(b.storage())

False

Создайте тензор c = b[1:,1:] Попробуйте догадаться, какими будут его размер, сдвиг и шаг, а потом проверьте свои догадки

In [219]:
c = b[1:, 1:]

In [220]:
c

tensor([[4, 5],
        [7, 8]])

In [221]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [222]:
c.stride() #шаг

(3, 1)

In [223]:
c.storage_offset() #сдвиг

4

Выберите какую-либо математическую операцию, например косинус или корень квадратный.
Примените эту функцию поэлементно к тензору a

In [224]:
a = torch.cos(a.float())

In [225]:
a

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [226]:
a = torch.cos_(a.float())

In [227]:
a

tensor([0.5403, 0.8576, 0.9147, 0.5487, 0.7939, 0.9600, 0.5734, 0.7290, 0.9894])

In [228]:
a.storage()

 0.5403022766113281
 0.857553243637085
 0.9146533012390137
 0.5486961007118225
 0.7938734292984009
 0.9600369334220886
 0.5733804702758789
 0.7290233373641968
 0.9894335269927979
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 9]

In [231]:
a.cos_()

tensor([0.6543, 0.7935, 0.8196, 0.6576, 0.7641, 0.8400, 0.6674, 0.7345, 0.8530])