<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Добавление-измерения-во-времени" data-toc-modified-id="Добавление-измерения-во-времени-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Добавление измерения во времени</a></span></li><li><span><a href="#Компоновка-данных-по-периоду-времени" data-toc-modified-id="Компоновка-данных-по-периоду-времени-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Компоновка данных по периоду времени</a></span></li><li><span><a href="#Кодирование-и-нормализация" data-toc-modified-id="Кодирование-и-нормализация-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Кодирование и нормализация</a></span></li></ul></div>

In [1]:
import numpy as np
import torch

### Добавление измерения во времени

In [2]:
bikes_numpy = np.loadtxt(
    '/Users/alexfil/Desktop/PyTorch/data/bike_sharing/hour-fixed.csv',
    dtype=np.float32,
    delimiter=',',
    skiprows=1,
    converters={1: lambda x: float(x[8:10])}) #  преобразование даты в числа 

In [4]:
bikes = torch.from_numpy(bikes_numpy)
bikes.shape, bikes

(torch.Size([17520, 17]),
 tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
          1.6000e+01],
         [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
          4.0000e+01],
         [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
          3.2000e+01],
         ...,
         [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
          9.0000e+01],
         [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
          6.1000e+01],
         [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
          4.9000e+01]]))

### Компоновка данных по периоду времени

In [5]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [6]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [7]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

### Кодирование и нормализация

In [8]:
first_day = bikes[:24].long()

In [10]:
first_day.shape, first_day

(torch.Size([24, 17]),
 tensor([[  1,   1,   1,   0,   1,   0,   0,   6,   0,   1,   0,   0,   0,   0,
            3,  13,  16],
         [  2,   1,   1,   0,   1,   1,   0,   6,   0,   1,   0,   0,   0,   0,
            8,  32,  40],
         [  3,   1,   1,   0,   1,   2,   0,   6,   0,   1,   0,   0,   0,   0,
            5,  27,  32],
         [  4,   1,   1,   0,   1,   3,   0,   6,   0,   1,   0,   0,   0,   0,
            3,  10,  13],
         [  5,   1,   1,   0,   1,   4,   0,   6,   0,   1,   0,   0,   0,   0,
            0,   1,   1],
         [  6,   1,   1,   0,   1,   5,   0,   6,   0,   2,   0,   0,   0,   0,
            0,   1,   1],
         [  7,   1,   1,   0,   1,   6,   0,   6,   0,   1,   0,   0,   0,   0,
            2,   0,   2],
         [  8,   1,   1,   0,   1,   7,   0,   6,   0,   1,   0,   0,   0,   0,
            1,   2,   3],
         [  9,   1,   1,   0,   1,   8,   0,   6,   0,   1,   0,   0,   0,   0,
            1,   7,   8],
         [ 10,   1,   1

In [11]:
weather_onehot = torch.zeros(first_day.shape[0], 4)

In [12]:
weather_onehot

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
first_day[:, 9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [14]:
weather_onehot.scatter_(dim=1,
                        index=first_day[:,9].unsqueeze(1).long() - 1,
                        value=1.0
                       )

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [16]:
torch.cat((bikes[:24], weather_onehot), 1)[:2]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000],
        [ 2.0000,  1.0000,  1.0000,  0.0000,  1.0000,  1.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2200,  0.2727,  0.8000,  0.0000,  8.0000, 32.0000,
         40.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [17]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4, daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [21]:
daily_weather_onehot[:1]

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0.]]])

In [22]:
daily_weather_onehot.scatter_(1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [23]:
daily_weather_onehot[:1]

tensor([[[1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
          1., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.]]])

In [24]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)

In [30]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [31]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - temp_min) 
                         / (temp_max - temp_min))

In [32]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp))
                         / torch.std(temp))